#!/bin/bash

# Title: Bug Hunt
# Description: Script to install various bug hunting tools on Termux

# Exit immediately if a command exits with a non-zero status
set -e

# Update and upgrade Termux packages
pkg update -y && pkg upgrade -y

# Install necessary tools
pkg install -y git curl wget python python2 ruby

# GitHub base URL
GITHUB_BASE_URL="https://github.com/user"

# Function to clone and install a tool
install_tool($1) {
    local tool_Bug-hunt repo=$1
    git clone "${GITHUB_BASE_URL}/${tool_Bug-hunt repo}.git"
    cd "${tool_Bug-hunt repo}"
    chmod +x install.sh
    ./install.sh
    cd ..
}

# Install tools
install_tool "file-chasser"
install_tool "netripper"
install_tool "net-trace"
install_tool "log-trace"
install_tool "kernel-trace"
install_tool "endpoint-hunter"
install_tool "code-bracker"

# Install Metasploit
pkg install -y unstable-repo
pkg install -y metasploit

# Install TheFatRat
git clone https://github.com/Screetsec/TheFatRat.git
cd TheFatRat
chmod +x setup.sh
./setup.sh
cd ..

# Install Bruteforce tools
pkg install -y hydra ncrack john

# Uncomment the following lines to install ImageMagick and process images
# pkg install -y imagemagick
# convert input_image.png -resize 800x600 output_image.png

# Clean up
apt autoremove -y
apt clean
